name: Demo Workflow
on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  PROJECT_NAME: test
  S3_BUCKET_NAME: anil-ci-artifacts

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Build Artifact to S3
        uses: anilrajrimal1/s3-build-artifact-uploader@v1.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.S3_BUCKET_NAME }}
          project-name: ${{ env.PROJECT_NAME }}
          zip-name: ${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_number }}.zip
